### ISSUE TITLE
Routing using Weighted Nodes

### ISSUE THREAD

**Issue by allenkaplan** [Inder-Dhillon/Toronto-Accidents-As-A-Network#6]
- [ ] Weight nodes
- [ ] Route with DBSCAN before weight
- [ ] Route with DBSCAN after weighting
- [ ] Compare to Google's route

Example Route: Bayview and Steeles to Keele and St. Clair

**Comment by harruup** [comment]
3 types of routes generated: by time, by distance, by injury_index. For now, the source and destination are provided as node id, we can use the coordinates and easily map it to the nodes in the network.
Working on adding street names to the nodes.

@AllenKaplan isn't DBSCAN is for clustering rather than routing?
